name: build-app_arm-gcc
on: [push]

jobs:
  test-lib-core:
    runs-on: ubuntu-latest
    steps:
      - name: get-cmake
        uses: lukka/get-cmake@latest
      - name: checkout-repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build-app
        run: |
          cd ${{ github.workspace }}
          chmod +x tools/build_app.sh
          ./tools/build_app.sh
