name: test-lib-core
on: [push]

jobs:
  test-lib-core:
    runs-on: ubuntu-latest
    steps:
      - name: get-cmake
        uses: lukka/get-cmake@latest
      - name: check-cmake
        run: |
          cmake --version
          ninja --version  
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: build-core-lib
        run: |
          cd ${{ github.workspace }}
          ./tools/build_tests.sh
      - name: test-core-lib
        run: ./build/tests/cmake-stm32l4-example_tests
