name: test-lib-core
on: [push]
jobs:
  build-core-lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./tools/build_tests.sh
  test-core-lib:
    runs-on: ubuntu-latest
    needs: build-core-lib
    steps:
      - uses: actions/checkout@v2
      - run: ./build/tests/cmake-stm32l4-example_tests
